### PR TITLE
Get short term ERS tests to work

### LINKED ISSUE #14: Exact restart (ERS) tests are failing
All of my attempts at running ERS tests have failed for various reasons. This includes both DEBUG on and off.

ERS.f19_g16.H_MML_2000_CAM6.cheyenne_gnu.clm-global_uniform_g16_SOM		
ERS.f19_g16.H_MML_2000_CAM6.cheyenne_intel.clm-global_uniform_g16_SOM		
ERS.f19_g17.F2000Cam6SlimRsGs.cheyenne_intel.clm-2000_CMIP6_AMIP_1deg_ensemble		
ERS_D.f19_g16.H_MML_2000_CAM5_BGC.cheyenne_gnu.clm-global_uniform_g16_SOM		
ERS_D.f19_g16.H_MML_2000_CAM6.cheyenne_gnu.clm-global_uniform_g16_SOM		
ERS_D.f19_g16.H_MML_2000_CAM6.cheyenne_intel.clm-global_uniform_g16_SOM		
ERS_D.f19_g17.F2000Cam6SlimRsGs.cheyenne_intel.clm-2000_CMIP6_AMIP_1deg_ensemble		
ERS_D.f19_g17.I1850Clm45BgcGs.cheyenne_intel.clm-realistic_fromCLM5_1850		
ERS_D.f19_g17.IHistClm45BgcQianGs.cheyenne_gnu.clm-realistic_fromCLM5_1850		
ERS_D.f19_g17.IHistClm45BgcQianGs.cheyenne_intel.clm-realistic_fromCLM5_1850

Most of these match with a smoke (SMS) test that does PASS. The exact reason seems to vary by the test case.

### PR DESCRIPTION
**Pull request by slevisconsulting**
Resolves #14 #65 

The correction seems to boil down to a single if statement that uses a ctsm time manager function.

I will add a short term ERS test (previously failing) to the SLIM test-suite.

I will run the full test-suites on cheyenne and izumi to make sure I didn't break anything.

### CODE REVIEW

File: src/biogeophys/mml_main.F90 [hunk 1]
```diff
@@ -522,45 +523,25 @@ subroutine mml_main (bounds, atm2lnd_inst, lnd2atm_inst) !lnd2atm_inst
...
- 					soil_tk_1d(begg:endg), soil_cv_1d(begg:endg), &
- 					glc_tk_1d(begg:endg), glc_cv_1d(begg:endg)   ) !, &
-
-                       !write(iulog,*)'read netcdf'
- 					
-		end if
-	call t_stopf('mml_nc_import')
-	
+     call t_startf('mml_nc_import')
+     if (is_first_step_of_this_run_segment()) then
```
Comment (slevisconsulting) [inline src/biogeophys/mml_main.F90:529]: This if statement is the only real change. The rest are changes to follow ctsm formatting.

File: cime_config/testdefs/testlist_clm.xml [hunk 2]
```diff
@@ -34,6 +34,15 @@
       <option name="comment">smoke test with SOM for CAM5 at 1850 (historical starting in 1850) saving cplhist files</option>
     </options>
   </test>
+  <test name="ERS_D_Ld3" grid="f19_g16" compset="H_MML_2000_CAM5" testmods="clm/global_uniform_g16_SOM">
```
Comment (slevisconsulting) [inline cime_config/testdefs/testlist_clm.xml:37]: I based this short term ERS test on its longer counterpart below.

I have submitted the cheyenne test-suite to find out whether my code-change broke anything. If all still works, then I will be in touch with you @ekluzek to discuss two questions:
1) Do we still need the ERS_D_Ld60 test now that the shorter test works?
2) While we're updating the testlist, do we want to include the changes needed for f45 and f10 here or do you prefer that I open a separate PR for clarity?

Comment (slevisconsulting) [reply cime_config/testdefs/testlist_clm.xml:37]: The gnu tests have completed and answers have changed in the longer tests relative to their baselines:
```
SMS_Lm3.f19_g16.H_MML_2000_CAM5.cheyenne_gnu.clm-global_uniform_g16_SOM BASELINE slim-n15_cesm2.1.4

ERS_D_Ld60.f19_g16.H_MML_2000_CAM5.cheyenne_gnu.clm-global_uniform_g16_SOM COMPARE_base_rest
ERS_D_Ld60.f19_g16.H_MML_2000_CAM5.cheyenne_gnu.clm-global_uniform_g16_SOM BASELINE slim-n15_cesm2.1.4
```
I don't know why offhand but @ekluzek I think your [comment in issue #14](url) about when the model reads the mml_surdat file is relevant here.

Comment (slevisconsulting) [reply cime_config/testdefs/testlist_clm.xml:37]: During SLIM Standup with @ekluzek and @fischer-ncar we realized that @marysa was intentionally calling nc_import every month, so my current solution is incorrect, which also explains why answers have changed for tests longer than one month.

Comment (marysa) [reply cime_config/testdefs/testlist_clm.xml:37]: Yes, I call nc_import every month because the surface properties that the user prescribes are allowed to be different for each month of the year. If there is a way to just call it once at the start of a run and store that monthly-varying information for the duration of the run, that would work also, but I didn't know how to do that across runs of arbitrary length (a few days vs a few months vs a few years), so instead I just had it go and explicitly grab that information from the netcdf file over and over. I'm sure there is a sneakier way to do this, I just didn't (and still don't) know how.

Comment (ekluzek) [reply cime_config/testdefs/testlist_clm.xml:37]: Thanks for explaining the desired behavior @marysa that helps. There are different ways to do this, but should start with what you have and do something different if there's a reason to change it.

File: src/biogeophys/mml_main.F90 [hunk 3]
```diff
@@ -522,45 +521,28 @@ subroutine mml_main (bounds, atm2lnd_inst, lnd2atm_inst) !lnd2atm_inst
...
-                       !write(iulog,*)'read netcdf'
- 					
-		end if
-	call t_stopf('mml_nc_import')
-	
+     call t_startf('mml_nc_import')
+     ! Read mml_surdat file at the beginning of a run and at the
+     ! beginning of the first day of every month
+!    if (is_first_step_of_this_run_segment() .or. (is_beg_curr_day() .and. day == 1)) then
+     if (is_first_step_of_this_run_segment() .or. (day == 1 .and. sec <= 1800)) then
```
Comment (slevisconsulting) [inline src/biogeophys/mml_main.F90:530]: I put back the if-clause that @marysa had, and the test-suite now passes against baselines. This means that the model now reads mml_surdat files in the first timestep of any simulation, plus at the beginning of every month, as Marysa intended.

Now the question is whether to replace Marysa's if-clause with the one that I have proposed in new line 529. Note that something about my choice changes answers relative to baselines in our 60-day tests. I agree with @marysa that `sec <= 1800` is causing the model to read the data twice. I also suspect that the first "read" is getting data from the new month one timestep too soon, hence causing the change in answers when I test my version.

Comment (slevisconsulting) [reply src/biogeophys/mml_main.F90:530]: @ekluzek suggested replacing 1800 with dt.
Then merge as is and open an issue explaining the suggested modification and the likely reason it's changing answers.

**Comment by slevisconsulting** [comment]
@ekluzek I will send you a review request and will post comments to indicate areas of potential concern on my part.

File: bld/config_cache.xml [hunk 4]
```diff
@@ -25,5 +25,8 @@ User source directories to prepend to the filepath.  Multiple directories
 are specified as a comma separated list with no embedded white space.
 Normally this is SourceMods/src.clm in your case.
 </entry>
+<entry id="hgrid" value="1.9x2.5" list="" valid_values="1.9x2.5,4x5,10x15">
```
Comment (slevisconsulting) [inline bld/config_cache.xml:28]: @ekluzek 
This is one of my concerns:
I thought I needed to add an entry for hgrid here, but it didn't help automate the selection of the mml_surdat file for the case's resolution. Maybe I'm missing code elsewhere...

File: bld/namelist_files/namelist_defaults_clm4_5.xml [hunk 5]
```diff
@@ -87,11 +87,14 @@ attributes from the config_cache.xml file (with keys converted to upper-case).
...
-<!-- MML data sets; currently only 2 degree, should add 1degree --> 
+<!-- MML data sets; should add 1degree --> 
 <!-- for any year (2000 or 1850) -->
-<mml_surdat>lnd/slim/surdat/mml_1.9x2.5_default_cdf5_c20211105.nc</mml_surdat>
+<mml_surdat hgrid="1.9x2.5">
+lnd/slim/surdat/mml_1.9x2.5_default_cdf5_c20211105.nc</mml_surdat>
+<mml_surdat hgrid="4x5">
+lnd/slim/surdat/slim_realistic_f19_20190110_cutout_to_f45_c20230131.nc</mml_surdat>
+<mml_surdat hgrid="10x15">
+lnd/slim/surdat/slim_realistic_f19_20190110_cutout_to_f10_c20230131.nc</mml_surdat>
```
Comment (slevisconsulting) [inline bld/namelist_files/namelist_defaults_clm4_5.xml:97]: I added the new mml_surdat file names above and distinguished them from the existing one (f19) by hgrid. This along with adding hgrid to config_cache.xml did not help automate the selection of the mml_surdat file for the case's resolution.

File: cime_config/testdefs/testlist_clm.xml [hunk 6]
```diff
@@ -34,6 +34,40 @@
       <option name="comment">smoke test with SOM for CAM5 at 1850 (historical starting in 1850) saving cplhist files</option>
     </options>
   </test>
+  <test name="ERS_D_Ld3" grid="f45_g37" compset="I2000SlimRsGs" testmods="clm/f45">
+    <machines>
+      <machine name="izumi" compiler="gnu"   category="aux_slim"/>
+      <machine name="izumi" compiler="nag"   category="aux_slim"/>
+      <machine name="izumi" compiler="intel" category="aux_slim"/>
+      <machine name="cheyenne" compiler="gnu"   category="aux_slim"/>
+      <machine name="cheyenne" compiler="intel" category="aux_slim"/>
```
Comment (slevisconsulting) [inline cime_config/testdefs/testlist_clm.xml:43]: Total five new f45 ERS_D_Ld3 tests, all listed above:
- 3 izumi compilers
- 2 cheyenne compilers
- all 5 for I-cases because the F-case that I tried failed with the following message:

```
Errors were:
        Building test for ERS in directory /glade/scratch/slevis/ERS_D_Ld3.f45_g37.F2000Cam6SlimRsGs.cheyenne_intel.clm-f45.20230223_094441_7c02ed
        Exception during build:
        ERROR: Command /glade/work/slevis/git_slim/SimpleLand/components/cam/bld/build-namelist -ntasks 36 -csmdata /glade/p/cesmdata/cseg/inputdata -infile /glade/scratch/slevis/ERS_D_Ld3.f45_g37.F2000Cam6SlimRsGs.cheyenne_intel.clm-f45.20230223_094441_7c02ed/Buildconf/camconf/namelist -ignore_ic_year -use_case 2000_cam6 -inputdata /glade/scratch/slevis/ERS_D_Ld3.f45_g37.F2000Cam6SlimRsGs.cheyenne_intel.clm-f45.20230223_094441_7c02ed/Buildconf/cam.input_data_list -namelist " &atmexp /"  failed rc=255
        out=CAM build-namelist - ERROR: No default value found for ncdata
        user defined attributes:
        key=ic_md  val=00010101
        err=Died at /glade/work/slevis/git_slim/SimpleLand/components/cam/bld/build-namelist line 4054.
        Traceback (most recent call last):
          File "/glade/work/slevis/git_slim/SimpleLand/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 86, in build
            model_only=(phase_name==MODEL_BUILD_PHASE))
          File "/glade/work/slevis/git_slim/SimpleLand/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 117, in build_phase
            self.build_indv(sharedlib_only=sharedlib_only, model_only=model_only)
          File "/glade/work/slevis/git_slim/SimpleLand/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 126, in build_indv
            save_build_provenance=not model=='cesm')
```
I decided not to investigate this because the F-case works with the f10 grid.

File: cime_config/testdefs/testlist_clm.xml [hunk 7]
```diff
@@ -34,6 +34,40 @@
...
+    <options>
+      <option name="wallclock">00:20:00</option>
+      <option name="comment">Short term debug restart test with I case at f45 resolution</option>
+    </options>
+  </test>
+  <test name="ERS_D_Ld3" grid="f10_f10_mg37" compset="I2000SlimRsGs" testmods="clm/f10">
+    <machines>
+      <machine name="izumi" compiler="gnu"   category="aux_slim"/>
+      <machine name="izumi" compiler="nag"   category="aux_slim"/>
+      <machine name="izumi" compiler="intel" category="aux_slim"/>
```
Comment (slevisconsulting) [inline cime_config/testdefs/testlist_clm.xml:54]: Three of five new f10 Ld3 tests:
- on the three izumi compilers
- all three for I-cases because I saw that none of the test-suite's existing F-cases were on izumi

File: cime_config/testdefs/testlist_clm.xml [hunk 8]
```diff
@@ -34,6 +34,40 @@
...
+    </machines>
+    <options>
+      <option name="wallclock">00:20:00</option>
+      <option name="comment">Short term debug restart test with I case at f10 resolution on izumi</option>
+    </options>
+  </test>
+  <test name="ERS_Ld3" grid="f10_f10_mg37" compset="F2000Cam6SlimRsGs" testmods="clm/f10">
+    <machines>
+      <machine name="cheyenne" compiler="gnu"   category="aux_slim"/>
+      <machine name="cheyenne" compiler="intel" category="aux_slim"/>
```
Comment (slevisconsulting) [inline cime_config/testdefs/testlist_clm.xml:64]: Two of five new f10 Ld3 tests:
- on the two cheyenne compilers
- both for F-cases since I couldn't use F-cases for f45 or izumi (as far as I could tell)

File: cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm [hunk 9]
```diff
@@ -0,0 +1 @@
+mml_surdat = '/glade/p/cesmdata/inputdata/lnd/slim/surdat/slim_realistic_f19_20190110_cutout_to_f10_c20230131.nc'
```
Comment (slevisconsulting) [inline cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm:1]: Since I didn't figure out how to automate the selection of the mml_surdat file for the case's resolution, I added /f45 and /f10 testmods directories. This works, and I have already generated baselines for these tests. I will be happy to rerun the f45 and f10 tests if there's a more elegant way to automate the selection of the mml_surdat file for the case's resolution.

Comment (slevisconsulting) [reply cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm:1]: This ends my list of comments.
@ekluzek I will wait for your feedback before running the izumi test-suite and subsquently merging this PR.

Comment (slevisconsulting) [reply cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm:1]: @ekluzek showed me a solution and I can remove testmod dirs for f45, f10, and 1-degree

File: src/biogeophys/mml_main.F90 [hunk 10]
```diff
@@ -522,45 +521,33 @@ subroutine mml_main (bounds, atm2lnd_inst, lnd2atm_inst) !lnd2atm_inst
...
+     call t_startf('mml_nc_import')
+     ! Read mml_surdat file at the beginning of a run and at the
+     ! beginning of the first day of every month
+     ! TODO (slevis) Current if statement maintains same answers with
+     ! baselines and fixes problem with short restart tests (less than
+     ! one month). Preferred solution may be something like
+     ! if (is_first_step_of_this_run_segment() .or. (is_beg_curr_day() .and. day == 1)) then
+     ! but we need to test it before deciding. An corresponding issue will
+     ! be opened.
+     if (is_first_step_of_this_run_segment() .or. (day == 1 .and. sec <= dt)) then
```
Comment (slevisconsulting) [inline src/biogeophys/mml_main.F90:535]: @ekluzek suggests testing sec == dt
- If this doesn't change answers, then use it
- If it changes answers, don't use it 

and add the information to #70

File: cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm (hunk 9 above)
Comment (slevisconsulting) [reply cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm:1]: Turns out the testmods dirs that say `2000_CMIP6_AMIP_1deg_ensemble` use a 2-degree surdat, so in the end I will just rename them to reduce confusion, but will not eliminate them. They use this surdat file:
`/glade/p/cesmdata/inputdata/lnd/slim/surdat/slim2deg_fromCMIP6-AMIP-1deg_ensemble001-010_1991to2010clim_max-ctrl-bucket_rs150_c20210401.nc`

Comment (ekluzek) [reply cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm:1]: Ahh, do we have any true 1-degree tests then? If not we should add some as well as the low resolution.

File: src/biogeophys/mml_main.F90 (hunk 10 above)
Comment (slevisconsulting) [reply src/biogeophys/mml_main.F90:535]: > However, though I expected otherwise, the same test with sec == 0 did not change answers, so I will use that. I will update and close #70.

To explain (I think exactly as @marysa had determined):
1) Marysa's code was reading every month at sec = 0 and sec = 1800.
2) My suggestion using is_beg_curr_day was the same as Erik's using sec == dt. This changed answers because Marysa's code was already reading the next month at sec == 0, while the new code was waiting for sec == 1800.
3) The current solution sec == 0 replicates the behavior of Marysa's code without re-reading the data at sec = 1800. Marysa, I think you knew all this, and I ended up figuring it out all over again. In any case, we've solved it.

File: cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm (hunk 9 above)
Comment (slevisconsulting) [reply cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm:1]: I added an f09 test and got this message:
`ERROR: LND_NTHRDS must be 1 as threading isn't implemented (see issue #14)`

I will try to find where LND_THREADS gets set, unless this is something easy for you to point out @ekluzek

Comment (ekluzek) [reply cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm:1]: It should be in the https://github.com/ESCOMP/SimpleLand/blob/cesm2_1_slim/cime_config/config_pes.xml file. But, it looks to me that f09 is handled and it doesn't have threading in it. So I'm not sure why running f09 would end up with nthreads>1....

Comment (slevisconsulting) [reply cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm]: I don't know either, but I got past the build error by changing the test prefix to `ERS_Ld3_P36x1`

Comment (slevisconsulting) [reply cime_config/testdefs/testmods_dirs/clm/f10/user_nl_clm]: @ekluzek @slevisconsulting 
found in README.case that the model gets its pelayout from cam, so we will settle for the solution of prescribing the pelayout in the testname. However, increase from 36 tasks to 144 (f19 is using 72).

**Comment by slevisconsulting** [comment]
Test-suite and new baseline on cheyenne: DONE
Test-suite and new baseline on izumi: DONE

Next I will merge this PR and make a new tag.
